### ISSUE TITLE
193行目からのfor文がうまく回っていない

### ISSUE THREAD

**Issue by haruna-yoshida** [RYoTA1209/NLP-Container#24]
# 概要
「何」を含む項がafterに分類される前にループを離脱してしまっているため、計算ができずエラーが出る。

# 再現手順
https://github.com/haruna-yoshida/NLP-Container/blob/main/test.py
for element in standard_list:から実行する。

#エラー内容
始め太郎くんは120円持っています。90円のお菓子を買うと何円残っていますか。
正規化処理完了
[('太郎', '120', '持っ', 2), ('お菓子', '90', '買う', 15), ('お菓子', '何', '買う', 15)]
共通概念処理完了
[('お菓子', '120', '持っ', 2), ('お菓子', '90', '買う', 15), ('お菓子', '何', '買う', 15)]
Traceback (most recent call last):
  File "test.py", line 253, in <module>
    normalize_table = get_normalize_table(quest,node_features,node_surfaces)
  File "test.py", line 220, in get_normalize_table
    ans = mysum(table.before)+mysum(table.increase)-mysum(table.decrease)
  File "test.py", line 226, in mysum
    bsum += int(l[1])
ValueError: invalid literal for int() with base 10: '何'

# 修正しないとどう困るか
30番の問題「始め太郎くんは120円持っています。90円のお菓子を買うと何円残っていますか。」などが解けない

# 原因
恐らくfor文とif文の分岐がうまくいっていない

# 修正案
解決方法がわからない

**Comment by haruna-yoshida** [comment]
#原因
「何」を含むstandard_listの項がafterに分類されておらず、余った項をincreaseに分類してしまっていたため、計算段階で「何」は数字ではないことを指摘されていた

#解決方法」
increaseに余った項を分類する時にstandard_listからtableを引いた項の中に「何」を含む項がなければincreaseに追加するようにした
↓書き換えたコード
judge_list = list(set(standard_list)-set(table.all_list()))
    for j in judge_list:
        if "何" in j:
            continue
        else:
            if table.all_list() not in standard_list:
                table.increase.append(list(set(standard_list)-set(table.all_list())))
